# Umfang, Form und Abgabe {#sec-B-form}

Es gibt unterschiedliche Arten von wissenschaftlichen Arbeiten und an die unterschiedliche Anforderungen gestellt werden.

## Seminararbeit

Eine Seminararbeit soll einen Umfang von 10 bis max. 15 Textseiten haben (ohne Titelblatt, Inhalts-, Abbildungs- bzw. Literaturverzeichnis und ggf. Anhang). Tabellen und Abbildungen sind in den Text zu integrieren und zählen mit in die Seitenzählung. Die fertiggestellte Seminararbeit ist in digitalisierter Form per Upload auf Moodle oder per E-Mail zum vereinbarten Termin abzugeben.

Mit der Annahme eines Seminararbeitsthemas beginnt die Bearbeitungszeit. Tritt der:die Studierende vom Thema zurück, so ist dies dem:der Betreuer:in der Seminararbeit sofort und unter der Nennung von Gründen mitzuteilen. Der Abgabetermin ist unbedingt einzuhalten. Geschieht dies nicht, so wird die Arbeit mit nicht bestanden (5,0) bewertet. Sollte die Bearbeitung in der vorgegebenen Zeit aus triftigen und stichhaltigen Gründen in Ausnahmefällen nicht möglich sein, so ist beim Prüfungsamt unverzüglich eine Verlängerung vor Ablauf der Abgabefrist zu beantragen.

## Bachelorarbeit

Die Bachelorarbeit ist innerhalb des letzten Semesters fertig zu stellen. Sie sollte einen Umfang von mindestens 40 bis max. 60 Textseiten haben (ohne Titelblatt, Inhalts-, Abbildungs- bzw. Literaturverzeichnis und ggf. Anhang). Tabellen und Abbildungen sind in den Text zu integrieren und zählen mit in die Seitenzählung. In der Prüfungsordnung des Studiengangs Sozialmanagement (B.A.) an der Hochschule Nordhausen sind folgende Formalia festgelegt:

-   **Arbeitsformen**: Einzel-/Gruppenarbeit ist möglich. Bei Gruppenarbeiten ist auf eine eindeutige Zuordnung der Anteile der Autor:innen durch z.B. Angabe von Abschnitten, Seitenzahlen o.a. objektiven Kriterien zu achten.

-   **Sprache**: Die Bachelorarbeit kann in Deutsch oder Englisch verfasst werden.

-   Ein **Abstract** ist in der jeweils anderen Sprache am Anfang der Arbeit zu verfassen.

-   Es müssen die [**Regeln guter wissenschaftlicher Praxis**](https://www.dfg.de/de/grundlagen-themen/grundlagen-und-prinzipien-der-foerderung/gwp) beachtet werden.

-   **Titel** der Bachelorarbeit kann in begründeten Fällen einmal und nur innerhalb von vier Wochen nach Themenausgabe durch Prüfungsausschuss zurückgegeben werden (gilt nicht für Zweitversuch) (§ 11 Abs. 5 PO)

-   **Prüfungsanmeldung** ist jederzeit möglich. Die **Bearbeitungszeit** beträgt drei Monate (darf aber vier Wochen nicht unterschreiten). Eine **Verlängerung** ist bei nicht zu vertretenden Gründen max. vier Wochen möglich (§ 11 Abs. 6 PO).

-   **Abgabe**: Bachelorarbeiten sind in gebundener Form und in dreifacher Ausfertigung beim Prüfungsamt abzugeben. Zusätzlich ist die Arbeit in digitalisierter Form auf einem elektronischen Datenträger in einem lesbaren und passwortfreien Dateiformat (z.B. docx, pdf, txt) einzureichen (§ 11 Abs. 7 PO).

[\
](https://hs-nordhausen.gitbook.io/leitfaden/basics/seitengestaltung-und-layout)
