# Impressum {.unnumbered}

Die Hochschule Nordhausen ist eine Körperschaft des öffentlichen Rechts und wird durch den Präsidenten, Prof. Dr. Jörg Wagner, gesetzlich vertreten.
 
**Hochschule Nordhausen**

Prof. Dr. Jörg Wagner

Weinberghof 4

99734 Nordhausen

Tel.: +49 3631 420-101

Fax: +49 3631 420-810

E-Mail: praesident(a)hs-nordhausen.de

## Redaktionell verantwortlich/ Durchführung

Prof. Dr. Maik Arnold

Hochschule Nordhausen

Studienbereich Sozialmanagement

Weinberghof 4

99734 Nordhausen

## Kontakt
Telefon: +49 3631 420-522

Telefax: +49 3631 420-817

E-Mail: maik.arnold(a)hs-nordhausen.de

## Umsatzsteueridentifikationsnummer nach § 27a UStG: 
DE 813 563 219

## Zuständige Aufsichtsbehörde:

Thüringer Ministerium für Wirtschaft, Wissenschaft und Digitale Gesellschaft (TMWWDG)

Max-Reger-Straße 4-8

99096 Erfurt

## Bildnachweis

Bildarchiv der Hochschule Nordhausen

## Hinweise

Dieses Impressum gilt für die zentralen Informationsangebote der Verwaltung und des Präsidiums der Hochschule Nordhausen im WWW, die über die URL www.fh-nordhausen.de und www.hs-nordhausen.de erreichbar sind. Für alle anderen Seiten auf diesem WWW-Server liegt die redaktionelle Verantwortlichkeit bei den jeweiligen Stellen oder Personen, die die Seiten erstellt haben.

Die Texte und Fotos auf den Seiten, die auf dieses Impressum verweisen, sind urheberrechtlich geschützt. Das Kopieren dieser Dateien und ihre evtl. Veränderung sind daher ohne Genehmigung des Urhebers (Hochschule Nordhausen) nicht gestattet. Unberührt davon bleibt das “Kopieren” der Dateien auf den eigenen Rechner, um sich die WWW-Seiten auf einem Browser anzuschauen. Ausgenommen sind ebenfalls die Pressemitteilungen der Hochschule. Sie sind dem Inhalt nach von jedermann frei und ohne besondere Genehmigung weiterverwendbar.