# Welcome {.unnumbered .unlisted}

> "Nichts im Leben ist zu fürchten, es ist nur zu verstehen. Jetzt ist die Zeit, mehr zu verstehen, damit wir weniger fürchten."
>
> Marie Skłodowska-Curie

Dieser Leitfaden soll Ihnen das wissenschaftliche Schreiben erleichtern.

Im Studium steht man bei der Anfertigung von Seminar-, Bachelor- und Masterarbeiten häufig vor einer ziemlichen Herausforderung.

In diesem [Quarto Book](https://quarto.org/) geben wir Ihnen wissenswerte und relevante Informationen rund um die Gestaltung einer wissenschaftlichen Arbeit im Studienbereich Sozialmanagement an der Hochschule Nordhausen.

Der Leitfaden beinhaltet folgende Teile:

-   **Getting Started**: Bestandteile des wissenschaftlichen Arbeitens

-   **Basics**: Formale Anforderungen

-   **Advanced**: Weiterführende Fragen und Hinweise

# **Ziel dieses Leitfadens**

::: callout-note
Seminar-, Bachelor-, und Masterarbeiten sind **selbständig erstellte wissenschaftliche Arbeiten**, die im Allgemeinen die schriftliche Dokumentation eines ausgewählten Problembereichs umfassen. Damit weisen Studierende nach, dass sie wissenschaftliche Probleme **erkennen**, **untersuchen** und die Ergebnisse **klar darstellen** können. Sie sollen relevante Literatur verarbeiten und unterschiedliche Meinungen kritisch würdigen können. Des Weiteren sollen die Studierenden eigene Lösungsansätze entwickeln.
:::

Die genannten Arbeiten verlangen eine geistige Durchdringung, Aufarbeitung und schriftliche Darstellung eines komplexen fachlichen Stoffgebietes in einer begrenzten Zeit. Die Fähigkeit, diese Leistung erfolgreich zu erbringen, wird auch in der späteren Berufspraxis erwartet, etwa bei der

-   Anfertigung von Projektberichten,

-   Positionspapieren,

-   Strategieplänen,

-   Diskussionsvorlagen

-   und anderen Dokumenten im beruflichen Alltag.

Darüber hinaus bieten wissenschaftliche Arbeiten den Studierenden die Möglichkeit, methodische Kompetenzen zu vertiefen und sich intensiv mit einem spezifischen Forschungsfeld auseinanderzusetzen, das ihre wissenschaftliche Argumentationsfähigkeit, ihr kritisches Denken und ihre Problemlösungsfähigkeiten fördert.

::: callout-note
Der vorliegende Leitfaden soll dabei helfen, einen Überblick über die wichtigsten Anforderungen an die formale Gestaltung von Seminar-, Bachelor- und Masterarbeiten zu erlangen. Für detaillierte Hinweise und Erläuterungen zu Arbeitstechniken, Zeitplanungen etc. wird auf die [Häufig gestellte Fragen](14_faq.qmd) und die [weiterführende Literatur](References.qmd) verwiesen.
:::

**Zitiervorschlag**

Studienbereich Sozialmanagement (Hrsg.) (2024). *Leitfaden Wissenschaftliches Arbeiten*. (Version 0.1). Hochschule Nordhausen. <https://doi.org/10.5281/zenodo.13844669>

**Bildnachweise**

Prompting von Maik Arnold, Rendering durch Midjourney

**Creative Commons Licence**

[Leitfaden Wissenschaftliches Arbeiten](https://profmanagement.quarto.pub/leitfaden/) by Studienbereich Sozialmanagement, Hochschule Nordhausen is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
