# Vorwort {.unnumbered}

## History and License {.unnumbered}

Dieser Leitfaden wurde auf Basis bisher im Umlauf befindlicher Empfehlungen und Vorgaben des Studienbereichs Sozialmanagement an der Hochschule Nordhausen entwickelt.

Das Buch wird unter einer [Creative Commons CC BY-NC-SA 4.0 Lizenz](https://creativecommons.org/licenses/by-nc-sa/4.0/) veröffentlicht. Das bedeutet, dass dieses Buch wiederverwendet, geremixt, überarbeitet und weiterverbreitet (jedoch ohne kommerzieller Nutzung) werden kann, solange die Autorinnen, die Autoren angemessen genannt werden. Wenn Sie die ursprüngliche Version dieses Open Educational Resource (OER) Buches remixen oder modifizieren, müssen Sie alle Versionen unter derselben Lizenz (CC BY-SA) weiterverbreiten.

## Vorwort zur Version 0.1 {.unnumbered}

Herzlich Willkommen beim Leitfaden für das wissenschaftliches Arbeiten im Studienbereich Sozialmanagement. Diese Website, respektive das Buch wurde mit dem klaren Ziel entwickelt, Studierenden eine fundierte Unterstützung für die vielfältigen Anforderungen beim wissenschaftlichen Schreiben zu geben. In einer Welt, in der fundierte Forschung und präzise Kommunikation immer wichtiger werden, möchten wir Ihnen gezielt die Werkzeuge und das Wissen an die Hand geben, die Sie benötigen, um auch diese akademische Herausforderung - das wissenschaftliche Schreiben - erfolgreich zu meistern.

Dieser Leitfaden dient als praxisorientierte Ressource, der sich den spezifischen Anforderungen und Besonderheiten des Studiums annimmt. Wissenschaftliches Schreiben und die damit verbundenen Methoden entwickeln sich stetig weiter. Um Ihnen stets aktuelles Wissen und praxisrelevante Informationen zur Verfügung zu stellen, wird dieser Leitfaden regelmäßig aktualisiert. Die Qualität dieses Leitfadens hängt maßgeblich auch von Ihrer Rückmeldung und Ihren Erfahrungen ab. Sollten Sie Verbesserungsvorschläge haben, auf Unklarheiten stoßen oder feststellen, dass bestimmte Inhalte nicht ausreichend dargestellt sind, zögern Sie bitte nicht, uns zu kontaktieren. Ihr wertvolles Feedback ermöglicht es uns, den Leitfaden kontinuierlich zu verbessern und an die Bedürfnisse beim Studieren anzupassen.

Wir hoffen, dass dieser Leitfaden Ihnen nicht nur als Nachschlagewerk dient, sondern Sie auch inspiriert und motiviert, Ihre wissenschaftlichen Fähigkeiten weiterzuentwickeln. Wissenschaftliches Arbeiten ist eine essenzielle Kompetenz, die Sie nicht nur im Studium, sondern auch in Ihrer späteren beruflichen Laufbahn begleiten wird. Nutzen Sie die angebotenen Ressourcen und lassen Sie sich für das wissenschaftliche Arbeiten von uns begeistern.

Wir wünschen Ihnen viel Erfolg und Freude damit. Happy Writing!

Im Name des Teams des Studienbereichs Sozialmanagement

*Maik Arnold (Redaktion)\
25. September 2024*

## Colophon

Der Leitfaden wurde bewusst als Open Source Dokument mit entwickelt und wird mittels [RStudio](https://posit.co/download/rstudio-desktop/) regelmäßig über mit [GitHub Pages](https://pages.github.com/) aktualisiert zur Verfügung gestellt.

Dieses Buch wurde mithilfe von [Quarto Book](https://www.quarto.org) und [RMarkdown](https://rmarkdown.rstudio.com/) erstellt. Die Erstellung und Bearbeitung erfolgten in der integrierten Entwicklungsumgebung [RStudio](https://posit.co/download/rstudio-desktop/). Für das Layout und die finalen Druckversionen kam [LaTeX](https://www.latex-project.org/) zum Einsatz. Alle technischen Komponenten wurden sorgfältig ausgewählt, um die Inhalte mittels Open Source Technologie und in Form von Open Access professionell und ansprechend zu gestalten.
